name: Build Arkanoid EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pygame pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole arkanoid.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: arkanoid-exe
          path: dist/arkanoid.exe
